export const GET_CITIES_FROM_SERVER = 'GET_CITIES_FROM_SERVER';
export const SET_LIST_CITIES_OF_SERVER = 'SET_LIST_CITIES_OF_SERVER';

export const GET_WAREHOUSES_FROM_SERVER = 'GET_WAREHOUSES_FROM_SERVER';
export const SET_LIST_WAREHOUSES_OF_SERVER = 'SET_LIST_WAREHOUSES_OF_SERVER';
export const SET_FILTER_LIST_WAREHOUSES = 'SET_FILTER_LIST_WAREHOUSES';

export const CHANGE_INPUT_CITY_VALUE = 'CHANGE_INPUT_CITY_VALUE';

export const CHANGE_INPUT_WAREHOUSE_VALUE  = 'CHANGE_INPUT_WAREHOUSE_VALUE';

export const LOADING_ON = 'LOADING_ON';
export const LOADING_OFF = 'LOADING_OFF';
